name:    ephemeral
github:  "jacksoncooper/ephemeral"

extra-source-files:
- README.md

description: Review interesting vocabulary from your e-reader.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ephemeral-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ephemeral

tests:
  ephemeral-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ephemeral
