name:    ephemeral
github:  "jacksoncooper/ephemeral"

extra-source-files:
- README.md

description: Dredge up highlighted words from e-books.

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5.5.1

library:
  source-dirs: src

executables:
  ephemeral-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ephemeral

tests:
  ephemeral-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ephemeral
